# Generated by Django 4.2.30 on 2026-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('matchday', models.IntegerField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, max_length=50, null=True)),
                ('utc_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
    ]
