# Generated by Django 4.2.30 on 2026-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('icon_url', models.CharField(blank=True, max_length=50, null=True)),
                ('cl_spot', models.IntegerField(blank=True, null=True)),
                ('uel_spot', models.IntegerField(blank=True, null=True)),
                ('relegation_spot', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'leagues',
                'managed': False,
            },
        ),
    ]
