# Generated by Django 4.2.30 on 2026-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('founded_year', models.FloatField(blank=True, null=True)),
                ('stadium_id', models.IntegerField(blank=True, null=True)),
                ('league_id', models.IntegerField(blank=True, null=True)),
                ('coach_id', models.IntegerField(blank=True, null=True)),
                ('cresturl', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
    ]
