# Generated by Django 4.2.30 on 2026-06-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('score_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_time_home', models.IntegerField(blank=True, null=True)),
                ('full_time_away', models.IntegerField(blank=True, null=True)),
                ('half_time_home', models.IntegerField(blank=True, null=True)),
                ('half_time_away', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scores',
                'managed': False,
            },
        ),
    ]
